name: ExUnit

on:
  pull_request:
    branches: ["develop", "main"]
  push:
    branches: ["main", "develop", "feature.**"]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Setup Elixir & OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.0.1'
          elixir-version: '1.13.4'
      - uses: etothepiipower/setup-chromedriver@v1
      - name: Install asset dependencies
        run: |
          cd assets
          npm install 
      - name: Restore dependencies
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOSTNAME: localhost
          POSTGRES_PORT: 5432
